package myApp;

// Generated 21-feb-2015 12:11:17 by Hibernate Tools 3.4.0.CR1

/**
 * CentroId generated by hbm2java
 */
public class CentroId implements java.io.Serializable {

	private int idUniversidad;
	private int idCentro;

	public CentroId() {
	}

	public CentroId(int idUniversidad, int idCentro) {
		this.idUniversidad = idUniversidad;
		this.idCentro = idCentro;
	}

	public int getIdUniversidad() {
		return this.idUniversidad;
	}

	public void setIdUniversidad(int idUniversidad) {
		this.idUniversidad = idUniversidad;
	}

	public int getIdCentro() {
		return this.idCentro;
	}

	public void setIdCentro(int idCentro) {
		this.idCentro = idCentro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CentroId))
			return false;
		CentroId castOther = (CentroId) other;

		return (this.getIdUniversidad() == castOther.getIdUniversidad())
				&& (this.getIdCentro() == castOther.getIdCentro());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUniversidad();
		result = 37 * result + this.getIdCentro();
		return result;
	}

}
