package myApp;

// Generated 21-feb-2015 12:11:17 by Hibernate Tools 3.4.0.CR1

/**
 * Centro generated by hbm2java
 */
public class Centro implements java.io.Serializable {

	private CentroId id;
	private Universidad universidad;
	private String nombreCentro;
	private String descripcion;
	private String direccion;
	private String paginaWeb;
	private String telefono;

	public Centro() {
	}

	public Centro(CentroId id, Universidad universidad, String nombreCentro) {
		this.id = id;
		this.universidad = universidad;
		this.nombreCentro = nombreCentro;
	}

	public Centro(CentroId id, Universidad universidad, String nombreCentro,
			String descripcion, String direccion, String paginaWeb,
			String telefono) {
		this.id = id;
		this.universidad = universidad;
		this.nombreCentro = nombreCentro;
		this.descripcion = descripcion;
		this.direccion = direccion;
		this.paginaWeb = paginaWeb;
		this.telefono = telefono;
	}

	public CentroId getId() {
		return this.id;
	}

	public void setId(CentroId id) {
		this.id = id;
	}

	public Universidad getUniversidad() {
		return this.universidad;
	}

	public void setUniversidad(Universidad universidad) {
		this.universidad = universidad;
	}

	public String getNombreCentro() {
		return this.nombreCentro;
	}

	public void setNombreCentro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPaginaWeb() {
		return this.paginaWeb;
	}

	public void setPaginaWeb(String paginaWeb) {
		this.paginaWeb = paginaWeb;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
